---
- set_fact:
    config_nodes_list: []

- name: add config nodes to the list
  set_fact:
    config_nodes_list: "{{ config_nodes_list + [ item.value.private_ip | default(item.value.ip) ] }}"
  when:
    - item.value.roles is defined
    - item.value.roles.config is defined
    - contrail_configuration.CONTROLLER_NODES is not defined
  with_dict: "{{ hostvars['localhost']['instances'] }}"

- set_fact:
    control_nodes_list: []

- name: add control nodes to the list
  set_fact:
    control_nodes_list: "{{ control_nodes_list + [ item.value.private_ip | default(item.value.ip) ] }}"
  when:
    - item.value.roles is defined
    - item.value.roles.control is defined
    - contrail_configuration.CONTROLLER_NODES is not defined
  with_dict: "{{ hostvars['localhost']['instances'] }}"

- set_fact:
    configdb_nodes_list: []

- name: add configdb nodes to the list
  set_fact:
    configdb_nodes_list: "{{ configdb_nodes_list + [ item.value.private_ip | default(item.value.ip) ] }}"
  when:
    - item.value.roles is defined
    - item.value.roles.config_database is defined
    - contrail_configuration.CONTROLLER_NODES is not defined
  with_dict: "{{ hostvars['localhost']['instances'] }}"

- set_fact:
    analytics_nodes_list: []

- name: add analytics nodes to the list
  set_fact:
    analytics_nodes_list: "{{ analytics_nodes_list + [ item.value.private_ip | default(item.value.ip) ] }}"
  when:
    - item.value.roles is defined
    - item.value.roles.analytics is defined
    - contrail_configuration.CONTROLLER_NODES is not defined
  with_dict: "{{ hostvars['localhost']['instances'] }}"

- set_fact:
    analyticsdb_nodes_list: []

- name: add analyticsdb nodes to the list
  set_fact:
    analyticsdb_nodes_list: "{{ analyticsdb_nodes_list + [ item.value.private_ip | default(item.value.ip) ] }}"
  when:
    - item.value.roles is defined
    - item.value.roles.analytics_database is defined
    - contrail_configuration.CONTROLLER_NODES is not defined
  with_dict: "{{ hostvars['localhost']['instances'] }}"

- set_fact:
    webui_nodes_list: []

- name: add webui nodes to the list
  set_fact:
    webui_nodes_list: "{{ webui_nodes_list + [ item.value.private_ip | default(item.value.ip) ] }}"
  when:
    - item.value.roles is defined
    - item.value.roles.webui is defined
  with_dict: "{{ hostvars['localhost']['instances'] }}"

- set_fact:
    k8s_master_nodes_list: []

- name: add k8s_master nodes to the list
  set_fact:
    k8s_master_nodes_list: "{{ k8s_master_nodes_list + [ item.value.private_ip | default(item.value.ip) ] }}"
  when:
    - item.value.roles is defined
    - item.value.roles.k8s_master is defined
  with_dict: "{{ hostvars['localhost']['instances'] }}"

- set_fact:
    k8s_node_nodes_list: []

- name: add k8s_node nodes to the list
  set_fact:
    k8s_node_nodes_list: "{{ k8s_node_nodes_list + [ item.value.private_ip | default(item.value.ip) ] }}"
  when:
    - item.value.roles is defined
    - item.value.roles.k8s_node is defined
  with_dict: "{{ hostvars['localhost']['instances'] }}"

- set_fact:
    openstack_nodes_list: []

- name: add openstack nodes to the list
  set_fact:
    openstack_nodes_list: "{{ openstack_nodes_list + [ item.value.private_ip | default(item.value.ip) ] }}"
  when:
    - item.value.roles is defined
    - item.value.roles.openstack is defined or item.value.roles.openstack_control is defined
  with_dict: "{{ hostvars['localhost']['instances'] }}"

- set_fact:
    vcenter_plugin_nodes_list: []

- name: add vcenter_plugin nodes to the list
  set_fact:
    vcenter_plugin_nodes_list: "{{ vcenter_plugin_nodes_list + [ item.value.private_ip | default(item.value.ip) ] }}"
  when:
    - item.value.roles is defined
    - item.value.roles.vcenter_plugin is defined
  with_dict: "{{ hostvars['localhost']['instances'] }}"

- set_fact:
    tsn_nodes_list: []

- name: add TSN nodes to the list
  set_fact:
    tsn_nodes_list: "{{ tsn_nodes_list + [ item.value.private_ip | default(item.value.ip) ] }}"
  when:
    - item.value.roles is defined
    - item.value.roles.vrouter is defined
    - item.value.roles.vrouter.TSN_EVPN_MODE is defined
    - item.value.roles.vrouter.TSN_EVPN_MODE | bool
  with_dict: "{{ hostvars['localhost']['instances'] }}"

