---
- name: Add VM DVS in a DC
  vmware_dvswitch:
    hostname: "{{ vc_server.hostname }}"
    username: "{{ vc_server.username }}"
    password: "{{ vc_server.password }}"
    validate_certs: "{{ vc_server.validate_certs }}"
    datacenter_name: "{{ vc_server.datacentername }}"
    switch_name: "{{ vc_server.dv_switch.dv_switch_name }}"
    switch_version: "{{ vc_server.dv_switch.dv_switch_version }}"
    mtu: "{{ vm_dvs_mtu | int}}"
    uplink_quantity: "{{ vm_dvs_uplink_qty | int}}"
    discovery_operation: "{{ vm_dvs_discovery_options }}"
    discovery_proto: "{{ vm_dvs_dic_proto }}"
    state: present

- name: Add DV-portgroup in vm dvs
  vmware_dvs_portgroup:
    hostname: "{{ vc_server.hostname }}"
    username: "{{ vc_server.username }}"
    password: "{{ vc_server.password }}"
    validate_certs: "{{ vc_server.validate_certs }}"
    portgroup_name: "{{ vc_server.dv_port_group.dv_portgroup_name }}"
    switch_name: "{{ vc_server.dv_switch.dv_switch_name }}"
    vlan_id: "{{ vm_dvs_vlan_id | int }}"
    num_ports: "{{ vm_dvs_num_ports | int }}"
    portgroup_type: "{{ vm_dvs_pg_type }}"
    state: present
# Use vm_dvs params for now
- name: Add control-data DVS in a DC
  vmware_dvswitch:
    hostname: "{{ vc_server.hostname }}"
    username: "{{ vc_server.username }}"
    password: "{{ vc_server.password }}"
    validate_certs: "{{ vc_server.validate_certs }}"
    datacenter_name: "{{ vc_server.datacentername }}"
    switch_name: "{{ vc_server.dv_switch_control_data.dv_switch_name }}"
    switch_version: "{{ vc_server.dv_switch_control_data.dv_switch_version }}"
    mtu: "{{ vm_dvs_mtu | int}}"
    uplink_quantity: "{{ vm_dvs_uplink_qty | int}}"
    discovery_operation: "{{ vm_dvs_discovery_options }}"
    discovery_proto: "{{ vm_dvs_dic_proto }}"
    state: present
  when: vc_server.dv_switch_control_data is defined and vc_server.dv_switch_control_data.dv_switch_name

- name: Add portgroup in control-data dvs
  vmware_dvs_portgroup:
    hostname: "{{ vc_server.hostname }}"
    username: "{{ vc_server.username }}"
    password: "{{ vc_server.password }}"
    validate_certs: "{{ vc_server.validate_certs }}"
    portgroup_name: "{{ vc_server.dv_port_group_control_data.dv_portgroup_name }}"
    switch_name: "{{ vc_server.dv_switch_control_data.dv_switch_name }}"
    vlan_id: "{{ vm_dvs_vlan_id | int }}"
    num_ports: "{{ vm_dvs_num_ports | int }}"
    portgroup_type: "{{ vm_dvs_pg_type }}"
    state: present
  when: vc_server.dv_switch_control_data is defined and vc_server.dv_switch_control_data.dv_switch_name

- name: Add mgmt DVS in a DC
  vmware_dvswitch:
    hostname: "{{ vc_server.hostname }}"
    username: "{{ vc_server.username }}"
    password: "{{ vc_server.password }}"
    validate_certs: "{{ vc_server.validate_certs }}"
    datacenter_name: "{{ vc_server.datacentername }}"
    switch_name: "{{ vc_server.dv_switch_mgmt.dv_switch_name }}"
    switch_version: "{{ vc_server.dv_switch_mgmt.dv_switch_version }}"
    mtu: "{{ vm_dvs_mtu | int}}"
    uplink_quantity: "{{ vm_dvs_uplink_qty | int}}"
    discovery_operation: "{{ vm_dvs_discovery_options }}"
    discovery_proto: "{{ vm_dvs_dic_proto }}"
    state: present
  when: vc_server.dv_switch_mgmt is defined and vc_server.dv_switch_mgmt.dv_switch_name

- name: Add portgroup in mgmt dvs
  vmware_dvs_portgroup:
    hostname: "{{ vc_server.hostname }}"
    username: "{{ vc_server.username }}"
    password: "{{ vc_server.password }}"
    validate_certs: "{{ vc_server.validate_certs }}"
    portgroup_name: "{{ vc_server.dv_port_group_mgmt.dv_portgroup_name}}"
    switch_name: "{{ vc_server.dv_switch_mgmt.dv_switch_name }}"
    vlan_id: "{{ vm_dvs_vlan_id | int }}"
    num_ports: "{{ vm_dvs_num_ports | int }}"
    portgroup_type: "{{ vm_dvs_pg_type }}"
    state: present
  when: vc_server.dv_switch_mgmt is defined and vc_server.dv_switch_mgmt.dv_switch_name

- name: Add sriov DVS in a DC
  vmware_dvswitch:
    hostname: "{{ vc_server.hostname }}"
    username: "{{ vc_server.username }}"
    password: "{{ vc_server.password }}"
    validate_certs: "{{ vc_server.validate_certs }}"
    datacenter_name: "{{ vc_server.datacentername }}"
    switch_name: "{{ vc_server.dv_switch_sr_iov.dv_switch_name }}"
    switch_version: "{{ vc_server.dv_switch_sr_iov.dv_switch_version }}"
    mtu: "{{ vm_dvs_mtu | int}}"
    uplink_quantity: "{{ vm_dvs_uplink_qty | int}}"
    discovery_operation: "{{ vm_dvs_discovery_options }}"
    discovery_proto: "{{ vm_dvs_dic_proto }}"
    state: present
  when: vc_server.dv_switch_sr_iov is defined and vc_server.dv_switch_sr_iov.dv_switch_name

- name: Add portgroup in sriov dvs
  vmware_dvs_portgroup:
    hostname: "{{ vc_server.hostname }}"
    username: "{{ vc_server.username }}"
    password: "{{ vc_server.password }}"
    validate_certs: "{{ vc_server.validate_certs }}"
    portgroup_name: "{{ vc_server.dv_port_group_sriov.dv_portgroup_name}}"
    switch_name: "{{ vc_server.dv_switch_sr_iov.dv_switch_name }}"
    vlan_id: "{{ vm_dvs_vlan_id | int }}"
    num_ports: "{{ vm_dvs_num_ports | int }}"
    portgroup_type: "{{ vm_dvs_pg_type }}"
    state: present
  when: vc_server.dv_switch_sr_iov is defined and vc_server.dv_switch_sr_iov.dv_switch_name
