---
- name: Reset the sriov_nics set_fact per VM
  set_fact:
    sriov_nics: ""

- name: Create sriov devices list
  set_fact:
    sriov_nics: "{{ sriov_nics | default () + nic + ',' }}"
  with_items: "{{ esxi_host.contrail_vm.sr_iov_nics }}"
  loop_control:
    loop_var: nic

- name: Add sriov nics
  vars:
    vmname: "ContrailVM-{{ esxi_host.vcenter_server.datacentername }}-{{ esxi_host.name }}"
  shell: "./add_pci_sriov_nics.py \
          --host \"{{ esxi_host.vcenter_server.hostname }}\" \
          --port {{ esxi_host.vcenter_server.port | default(vcenter_port) }} \
          --user \"{{ esxi_host.vcenter_server.username }}\" \
          --password \"{{ esxi_host.vcenter_server.password }}\" \
          --esxi_host \"{{ esxi_host.name }}\" \
          --esxi_user \"{{ esxi_host.username }}\" \
          --esxi_password \"{{ esxi_host.password }}\" \
          --sriov_nics \"{{ sriov_nics }}\" \
          --sriov_dvs \"{{ esxi_host.vcenter_server.dv_switch_sr_iov.dv_switch_name }}\" \
          --sriov_dvs_pg \"{{ esxi_host.vcenter_server.dv_port_group_sriov.dv_portgroup_name }}\" \
          --vm_name \"{{ esxi_host.contrail_vm.name | default (vmname) }}\""
  args:
    chdir: "{{role_path}}/tools"
  async: 3600
  poll: 0
  register: add_nics_result

- name: Save add_nics task results
  set_fact:
    sriov_nics_added: "{{ sriov_nics_added | default ([]) + [add_nics_result] }}"
