---
- name: Reset the pci_nics set_fact per VM
  set_fact:
    pci_nics: ""

- name: Create pci devices list
  set_fact:
    pci_nics: "{{ pci_nics | default () + nic + ',' }}"
  with_items: "{{ esxi_host.contrail_vm.pci_devices }}"
  loop_control:
    loop_var: nic

- name: Add pci nics
  vars:
    vmname: "ContrailVM-{{ esxi_host.vcenter_server.datacentername }}-{{ esxi_host.name }}"
  shell: "./add_pci_sriov_nics.py \
          --host \"{{ esxi_host.vcenter_server.hostname }}\" \
          --port {{ esxi_host.vcenter_server.port | default(vcenter_port) }} \
          --user \"{{ esxi_host.vcenter_server.username }}\" \
          --password \"{{ esxi_host.vcenter_server.password }}\" \
          --esxi_host \"{{ esxi_host.name }}\" \
          --esxi_user \"{{ esxi_host.username }}\" \
          --esxi_password \"{{ esxi_host.password }}\" \
          --pci_nics \"{{ pci_nics }}\" \
          --vm_name \"{{ esxi_host.contrail_vm.name | default (vmname) }}\""
  args:
    chdir: "{{role_path}}/tools"
  async: 3600
  poll: 0
  register: add_nics_result

- name: Save add_nics task results
  set_fact:
    pci_nics_added: "{{ pci_nics_added | default ([]) + [add_nics_result] }}"
