---
- name: Check ContrailVM deployed
  shell: "./check_contrailvm_deploy.py \
          --host \"{{ esxi_host.vcenter_server.hostname }}\" \
          --port {{ esxi_host.vcenter_server.port | default(vcenter_port) }} \
          --user \"{{ esxi_host.vcenter_server.username }}\" \
          --password \"{{ esxi_host.vcenter_server.password }}\" \
          --host_name \"{{ esxi_host.name }}\""
  args:
    chdir: "{{ role_path }}/tools"
  async: 3600
  poll: 5
  register: vm_check
  until: vm_check.stdout is defined and "deployed" in vm_check.stdout
  retries: 100

- name: Wait for contrailVm create completion
  async_status: jid={{ vm_check.ansible_job_id }}
  register: deploy_completed
  until: deploy_completed.finished
  retries: 100
  with_items: vm_check.results

