---
- name: Create clusters in DC
  vmware_cluster:
    hostname: "{{ vc_server.hostname }}"
    username: "{{ vc_server.username }}"
    password: "{{ vc_server.password }}"
    validate_certs: "{{ vc_server.validate_certs }}"
    datacenter_name: "{{ vc_server.datacentername }}"
    cluster_name: "{{ item }}"
    state: present
  with_items: "{{ vc_server.clusternames }}"
