---
- name: Fix VM DVS PG and add pvlan config
  shell: "./manage_dvs_pg.py \
          --host \"{{ vc_server.hostname }}\" \
          --port {{ vc_server.port | default(vcenter_port) }} \
          --user \"{{ vc_server.username }}\" \
          --password \"{{ vc_server.password }}\" \
          --dvs_name \"{{ vc_server.dv_switch.dv_switch_name }}\" \
          --dv_pg_name \"{{ vc_server.dv_port_group.dv_portgroup_name }}\" \
          --num_ports {{ vc_server.dv_port_group.number_of_ports }}"
  args:
    chdir: "{{ role_path }}/tools"
  async: 3600
  poll: 0
  register: sw_fixed

- name: Save VM dvs pvlan fix task results
  set_fact:
    dvs_fixed: "{{ dvs_fixed | default ([]) + [sw_fixed] }}"
