---
- name: Create temp file
  tempfile:
    suffix: temp.json
  register: filename

- name: Populate servers json
  shell: "server-manager display server --server_id {{esxi_host.id_in_sm}} -d -s >> {{filename.path}}"

- name: Get SM ip
  shell: cat /opt/contrail/server_manager/sm-config.ini | grep listen_ip_addr | awk '{print $3}'
  register: smipstr

- name: Get server mgmt ip
  shell: "server-manager display server --server_id {{esxi_host.id_in_sm}} --select ip_address |awk NR==4 |awk '{print $2}'"
  register: server_mgmt_ip

- name: Ensure server is reachable
  local_action: wait_for port=22 host={{server_mgmt_ip.stdout}} state=started delay=30 timeout=600
  sudo: false

- name: Run preconfig script
  #shell: "python /opt/contrail/server_manager/client/preconfig.py \
  shell: "./preconfig.py \
          --server-json {{filename.path}} --server-manager-ip {{smipstr.stdout}}"
  args:
    chdir: "{{role_path}}/tools"
