---
- hosts: deployer
  vars:
    kolla_dir: "{{ inventory_dir }}/../../contrail-kolla-ansible"
  tasks:
  - name: Clone openstack git repo
    git:
      repo: https://github.com/Juniper/contrail-kolla-ansible.git
      dest: "{{ kolla_dir }}"
      version: "contrail/{{ openstack_sku }}"
    ignore_errors: yes

