---
- name: set selinux to permissive
  selinux:
    policy: targeted
    state: permissive

# we need to remove python-requests installed by distutils
# cause it conflicts with requests lib installed by pip during docker-compose install
- name: remove python-requests installed by distutils
  package:
    name: python-requests
    state: absent
  register: res
  retries: 5
  until: res | success

- name: Install pip
  block:
    - name: Install easy_install
      package:
        name: python-setuptools
        state: present
      register: res
      retries: 5
      until: res | success
    - name: Install pip
      easy_install:
        name: pip
        state: latest
  when:
    - ansible_distribution != "RedHat"
    - ansible_distribution != "Red Hat Enterprise Linux"

# Do not use easy_install for RedHat. There is a bug that might cause
# easy_install to hang:
# https://github.com/ansible/ansible/issues/15769
# https://bugzilla.redhat.com/show_bug.cgi?id=1702797
# Use shell to intall pip for RedHat to work around the bug
- name: Install pip for Red Hat
  block:
    - name: Get pip installer
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py
    - name: Install pip
      shell: python /tmp/get-pip.py
      register: rc
      retries: 5
      until: rc | success
  when: (ansible_distribution == "RedHat" or ansible_distribution == "Red Hat Enterprise Linux")
