---

# this file is parameterized
# it takes 'docker_registry' as a parameter that should be added to insecure_registry list

- name: create docker config directory
  file:
    path: "{{ nix_docker_config_directory }}"
    state: directory
    mode: 0755

- name: ensure docker config file exists
  file:
    path: "{{ nix_docker_config_file }}"
    state: touch

- name: read docker config file
  shell: "cat {{ nix_docker_config_file }}"
  register: docker_daemon_file

- name: convert entries to json
  set_fact:
    docker_daemon: "{{ docker_daemon_file.stdout | default('{}', true) | from_json }}"

- name: register insecure-registries
  set_fact:
    insecure_registries: "{{ docker_daemon['insecure-registries'] | default([]) }}"

- name: add new docker_registry to docker config
  block:
    - name: insert updated insecure-registries to docker daemon
      set_fact:
        docker_daemon: "{{ docker_daemon | combine({ 'insecure-registries': insecure_registries + [docker_registry.split('/')[0]] }) }}"

    - name: write config to daemon.json
      copy:
        content: "{{ docker_daemon | to_nice_json }}"
        dest: "{{ nix_docker_config_file }}"

    - name: reload systemd
      shell: systemctl daemon-reload
      when: ansible_os_family == 'RedHat'

    - name: restart docker daemon
      service:
        enabled: yes
        name: docker
        state: restarted

  when: docker_registry.split('/')[0] not in insecure_registries
