---

- include: "{{ ansible_os_family }}.yml"

- name: add insecure registry
  include: insecure_registry.yaml
  when:
    - global_configuration is defined
    - global_configuration.CONTAINER_REGISTRY is defined
    - global_configuration.REGISTRY_PRIVATE_INSECURE is defined
    - global_configuration.REGISTRY_PRIVATE_INSECURE == true

- name: add private registry
  include: private_registry.yaml
  when:
    - global_configuration is defined
    - global_configuration.CONTAINER_REGISTRY is defined
    - global_configuration.REGISTRY_PRIVATE_SECURE is defined
    - global_configuration.REGISTRY_PRIVATE_SECURE == true

- name: start docker daemon
  service:
    enabled: yes
    name: docker
    state: started

- name: add private registry authentication
  include: auth_registry.yaml
  when:
    - global_configuration is defined
    - global_configuration.CONTAINER_REGISTRY is defined
    - global_configuration.CONTAINER_REGISTRY_USERNAME is defined
    - global_configuration.CONTAINER_REGISTRY_PASSWORD is defined
