---
- set_fact:
    cluster_roles_dict: {}

- name: Calculate Existing Roles
  set_fact:
    cluster_roles_dict: "{{ cluster_roles_dict | calculate_contrail_roles(config_nodes_list, instances, global_configuration, contrail_configuration, kolla_config | default(None), hostvars) }}"

- name: build deleted toragent roles
  set_fact:
      cluster_roles_dict: "{{ cluster_roles_dict | calculate_deleted_toragent_roles(item) }}"
  with_dict: "{{ instances }}"
  when:
    - global_configuration.ENABLE_DESTROY | default('True') | bool

- name: Fail if there was an Exception in getting data
  fail:
    msg:
      - "There was an exception when contacting the cluster:"
      - "{{ cluster_roles_dict['Exception'] }}"
  when: "'Exception' in cluster_roles_dict"

- name: Calculate node roles Dict
  set_fact:
    node_roles_dict: "{{ cluster_roles_dict['node_roles_dict'] }}"

- name: Calculate deleted role Dict
  set_fact:
    deleted_nodes_dict: "{{ cluster_roles_dict['deleted_nodes_dict'] }}"

- name: set api_server as validated active API server
  set_fact:
    api_server: "{{ cluster_roles_dict['api_server_ip'] }}"
