---
# Vcenter defaults
vcenter_port: 443
validate_certs: False

# Fab switch defaults
std_switch_name: vSwitch0
std_pg_name: fab-pg

# VM DVS defaults
dv_switch:
  dv_switch_name: vm_dvs
  dv_switch_version: 6.5.0
dv_port_group:
  dv_portgroup_name: vm_pg
  number_of_ports: 1800
vm_dvs_mtu: 1500
vm_dvs_uplink_qty: 8
vm_dvs_discovery_options: listen
vm_dvs_dic_proto: cdp

# VM DVS PG defaults
vm_dvs_vlan_id: 0
vm_dvs_num_ports: 3
vm_dvs_pg_type: earlyBinding

# ContrailVM deploy mode
auto_deploy: true

# Cluster HA, DRS and other config
enable_ha: no
enable_drs: no
