---
- name: Ensure sudo group is present
  group:
    name: sudo
    state: present
  become: True

- name: Ensure kolla group is present
  group:
    name: kolla
    state: present
  become: True

- name: Create kolla user
  user:
    name: kolla
    state: present
    group: kolla
    groups: "sudo"
  become: True

- name: Grant kolla user passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^kolla'
    line: 'kolla ALL=(ALL) NOPASSWD: ALL'
  become: True

- name: Packages needed for swift
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - parted
    - xfsprogs
  when:
    - kolla_globals.enable_swift | default('yes') | bool
  register: res
  retries: 5
  until: res | success

- name: Install configfs module needed for ironic on Debian hosts
  modprobe:
    name: configfs
    state: present
  when: ansible_os_family == 'Debian'
