---

- name: Create password file from template
  template:
    src: "{{ role_path }}/templates/passwords_{{ openstack_sku }}.yml.j2"
    dest: "{{ kolla_dir }}/etc/kolla/passwords.yml"
  delegate_to: localhost

- name: Generate kolla passwords
  command: "{{ kolla_dir }}/tools/generate_passwords.py -p {{ kolla_dir }}/etc/kolla/passwords.yml"
  register: pw_output
  failed_when: pw_output.rc != 0
  delegate_to: localhost
