---
kolla_globals: "{{ kolla_config.kolla_globals if kolla_config.kolla_globals is defined else default_kolla_globals}}"

os_nodes_storage: >-
     {%- set node_list = [] -%}
      {%- for k,v in hostvars['localhost']['instances'].items() -%}
       {%- if v.roles is not defined or v.roles.openstack is defined or v.roles.openstack_control is defined or v.roles.openstack_storage is defined -%}
        {%- if hostvars[v.ip]['ansible_' + hostvars[v.ip]['network_interface_detected']].get('ipv4',{}).get('address') -%}
         {%- do node_list.append(hostvars[v.ip]['ansible_' + hostvars[v.ip]['network_interface_detected']].get('ipv4',{}).get('address')) -%}
        {%- endif -%}
       {%- endif -%}
      {%- endfor -%}
      {{ node_list|join(',') }}

instance_data: "{{ instances[hostvars[inventory_hostname].instance_name] }}"
