---
- name: Clone openstack git repo
  git:
    repo: https://github.com/Juniper/contrail-kolla-ansible.git
    dest: "{{ kolla_dir }}"
    version: "contrail/{{ openstack_sku }}"
  ignore_errors: yes
  register: kolla_repo

- name: Revert kolla to given commit
  shell: "git reset --hard {{ kolla_config.commit_id }}"
  args:
    chdir: "{{ kolla_dir }}"
  when:
    - kolla_repo.changed
    - kolla_config.commit_id is defined

- name: Create configs customization dir
  file:
    path: "{{ '/etc/kolla/config/' + item.key | dirname }}"
    state: directory
    mode: 0755
    recurse: yes
  with_dict: "{{ kolla_config.customize | default({}) }}"

- name: Upload configs custimization
  copy:
    dest: "/etc/kolla/config/{{ item.key }}"
    content: "{{ item.value }}"
  with_dict: "{{ kolla_config.customize | default({}) }}"
