---
- name: Check openstack repo is present
  stat:
    path: "{{ kolla_dir }}"
  register: kolla_dir_stat

- name: Clone openstack git repo
  git:
    repo: https://github.com/Juniper/contrail-kolla-ansible.git
    dest: "{{ kolla_dir }}"
    force: "{{ force_checkout }}"
  ignore_errors: yes
  register: kolla_repo
  when: not kolla_dir_stat.stat.exists or force_checkout|bool

- name: Check current branch
  shell: "git rev-parse --abbrev-ref HEAD"
  args:
    chdir: "{{ kolla_dir }}"
  register: kolla_branch
  when:
      - kolla_dir_stat.stat.exists

- name: Choosing openstack branch
  shell: "git checkout contrail/{{ openstack_sku }}"
  args:
    chdir: "{{ kolla_dir }}"
  when:
      - kolla_dir_stat.stat.exists
      - kolla_branch != "contrail/{{ openstack_sku }}"

- name: Revert kolla to given commit
  shell: "git reset --hard {{ kolla_config.commit_id }}"
  args:
    chdir: "{{ kolla_dir }}"
  when:
    - kolla_repo is defined
    - kolla_repo.changed
    - kolla_config.commit_id is defined

- name: Create configs customization dir
  file:
    path: "{{ '/etc/kolla/config/' + item.key | dirname }}"
    state: directory
    mode: 0755
    recurse: yes
  with_dict: "{{ kolla_config.customize | default({}) }}"

- name: Upload configs custimization
  copy:
    dest: "/etc/kolla/config/{{ item.key }}"
    content: "{{ item.value }}"
  with_dict: "{{ kolla_config.customize | default({}) }}"
