provider_config:
  bms:
instances:
  bms1:
    provider: bms
    ip: 192.168.1.100
global_configuration:
  CONTAINER_REGISTRY: michaelhenkel
contrail_configuration:
  CONTRAIL_VERSION: queens-5.0-20180219195722
