---
contrail_dir: "{{ inventory_dir }}/../.."
contrail_config: {}

cnl: >-
  {%- set nl = [] -%}
  {%- for k,v in contrail_roles_for_nodes.iteritems() -%}
    {%- if 'control' in v -%}
      {{ nl.append(k) }}
    {%- endif -%}
    {%- if loop.last -%}
      {%- print nl -%}
    {%- endif -%}
  {%- endfor -%}

controller_nodes: "{{ cnl | join(',') }}"

contrail_roles:
  - config_database
  - config
  - control
  - webui
  - analytics
  - analytics_database
  - vrouter


default_contrail_configuration:
  contrail_configuration:
    CONTAINER_REGISTRY: opencontrailnightly
    CLOUD_ORCHESTRATOR: openstack
    CONTRAIL_VERSION: 5.0.0-134-centos7-ocata
    CONTROLLER_NODES: "{{ controller_nodes }}"
    PHYSICAL_INTERFACE: "{{ ansible_default_ipv4.interface }}"
    VROUTER_GATEWAY: "{{ ansible_default_ipv4.gateway }}"
    AUTH_MODE: keystone
    KEYSTONE_AUTH_ADMIN_PASSWORD: c0ntrail123
    KEYSTONE_AUTH_HOST: "{{ keystone_auth_host }}"
    KEYSTONE_AUTH_URL_VERSION: "/v3"
    RABBITMQ_NODE_PORT: 5673
  roles: "{{ contrail_roles_for_nodes }}"

default_config_all:
  BUILD_VMS: false
  CONFIGURE_VMS: false
  CREATE_CONTAINERS: true
  CENTOS_DOWNLOAD_URL: http://cloud.centos.org/centos/7/images/
  CENTOS_IMAGE_NAME: CentOS-7-x86_64-GenericCloud-1710.qcow2.xz
  CONTAINER_VM_ROOT_PWD: contrail123
  CONTAINER_VM_CONFIG:
    root_pwd: contrail123
    vcpu: 12
    vram: 64000
    vdisk: 100G
    network:
        subnet_prefix: 192.168.1.0
        subnet_netmask: 255.255.255.0
        gatway: 192.168.1.1
        nameserver: 10.84.5.100
        ntpserver: 192.168.1.1
        domainsuffix: local
