---

common_config:
  orchestrator: openstack
  openstack_sku: ocata
  # All nodes under target_nodes will be aded to all roles (both openstack and
  # contrail)
  #target_nodes:
  #  - 192.168.1.55 ansible_ssh_pass=c0ntrail123
  #  - 192.168.1.60 ansible_connection=local
  #  - 192.168.1.56 ansible_ssh_pass=c0ntrail123

#kolla_config:
#   Refer here for a list of all possible parameters that can be given under
#   kolla_globals:
#   https://github.com/Juniper/contrail-kolla-ansible/blob/contrail/ocata/etc/kolla/globals.yml
#   Intelligent defaults will be calculated based on common_config if not
#   specified
#  kolla_globals:
#    kolla_internal_vip_address: 192.168.1.160
#    kolla_external_vip_address: 192.168.1.60
#    contrail_api_interface_address: 192.168.1.60
#    network_interface: "eth1"
#    kolla_external_vip_interface: "eth1"
#   Uncomment this to distribute roles. The default is all roles in 'localhost'
#  openstack_roles:
#    control:
#      - "localhost ansible_connection=local"
#    network:
#      - "localhost ansible_connection=local"
#    compute:
#      - "localhost ansible_connection=local"
#    storage:
#      - "localhost ansible_connection=local"
#    monitoring:
#      - "localhost ansible_connection=local"
#    deployment:
#      - "localhost ansible_connection=local"

# Customize your contrail parameters by giving options under contrail_configuration.
# Refer here for a list of all possible parameters that can be tweaked:
# https://github.com/Juniper/contrail-container-builder/blob/master/containers/base/common.sh
contrail_config:
  inventory_hosts: |
    container_hosts:
      hosts:
        192.168.1.60:
           "ansible_connection: local"
  contrail_all:
    CONFIGURE_VMS: true
    CONTAINER_VM_CONFIG:
      network:
          ntpserver: 10.84.5.100
  container_hosts_openstack:
    contrail_configuration:
      CONTRAIL_VERSION: master-20180210000007-centos7-ocata
      CONTROLLER_NODES: 192.168.1.60
      KEYSTONE_AUTH_HOST: 192.168.1.60
      PHYSICAL_INTERFACE: eth2
      VROUTER_GATEWAY: 192.168.10.1
    roles:
      192.168.1.60:
        - config_database
        - config
        - control
        - webui
        - analytics
        - analytics_database
        - vrouter
