---
kolla_config: {}
default_openstack_sku: ocata
openstack_sku: >-
    {%- if contrail_configuration.OPENSTACK_VERSION is defined -%}
      {{ contrail_configuration.OPENSTACK_VERSION }}
    {%- elif kolla_config.kolla_globals is defined and kolla_config.kolla_globals.openstack_release is defined -%}
      {{ kolla_config.kolla_globals.openstack_release }}
    {%- else -%}
      {{ default_openstack_sku }}
    {%- endif -%}

kolla_dir: "{{ playbook_dir }}/../../contrail-kolla-ansible"
force_clone: >-
    {%- if kolla_config.kolla_globals is defined and kolla_config.kolla_globals.force_clone is defined -%}
      {{ kolla_config.kolla_globals.force_clone }}
    {%- else -%}
      no
    {%- endif -%}
force_checkout: >-
    {%- if kolla_config.kolla_globals is defined and kolla_config.kolla_globals.force_checkout is defined -%}
      {{ kolla_config.kolla_globals.force_checkout }}
    {%- else -%}
      no
    {%- endif -%}
