---
- name: start contrail config
  docker_service:
    project_name: contrail-config
    pull: yes
    definition:
      version: '2'
      services:
        network:
          image: docker.io/kubernetes/pause
          network_mode: "host"
          volumes:
           - /etc/hosts:/etc/hosts
        nodemgr:
          image: "{{ CONTAINER_REGISTRY }}/contrail-nodemgr:{{ contrail_configuration.CONTRAIL_VERSION }}"
          env_file: /tmp/common.env
          environment:
            - NODEMGR_TYPE=contrail-config
          network_mode: "service:network"
          volumes:
            - /var/log/contrail:/var/log/contrail
            - /var/run/docker.sock:/var/run/docker.sock
          depends_on:
            - network
          restart: on-failure
        api:
          image: "{{ CONTAINER_REGISTRY }}/contrail-controller-config-api:{{ contrail_configuration.CONTRAIL_VERSION }}"
          env_file: /tmp/common.env
          network_mode: "service:network"
          volumes:
            - /var/log/contrail:/var/log/contrail
          depends_on:
            - network
          restart: on-failure
        svcmonitor:
          image: "{{ CONTAINER_REGISTRY }}/contrail-controller-config-svcmonitor:{{ contrail_configuration.CONTRAIL_VERSION }}"
          network_mode: "service:network"
          env_file: /tmp/common.env
          volumes:
            - /var/log/contrail:/var/log/contrail
          depends_on:
            - network
          restart: on-failure
        schema:
          image: "{{ CONTAINER_REGISTRY }}/contrail-controller-config-schema:{{ contrail_configuration.CONTRAIL_VERSION }}"
          network_mode: "service:network"
          env_file: /tmp/common.env
          volumes:
            - /var/log/contrail:/var/log/contrail
          depends_on:
            - network
          restart: on-failure
        devicemgr:
          image: "{{ CONTAINER_REGISTRY }}/contrail-controller-config-devicemgr:{{ contrail_configuration.CONTRAIL_VERSION }}"
          network_mode: "service:network"
          env_file: /tmp/common.env
          volumes:
            - /var/log/contrail:/var/log/contrail
          depends_on:
            - network
          restart: on-failure
