---
- set_fact:
    cluster_roles_dict: {}

- name: Calculate Existing Roles
  set_fact:
    cluster_roles_dict: "{{ cluster_roles_dict | calculate_openstack_roles(instances, global_configuration|default({}), contrail_configuration, kolla_config, hostvars) }}"

- name: Fail if there was an Exception in getting data
  fail:
    msg:
      - "There was an exception when contacting the cluster:"
      - "{{ cluster_roles_dict['Exception'] }}"
  when: "'Exception' in cluster_roles_dict"

- name: Calculate node roles Dict
  set_fact:
    node_roles_dict: "{{ cluster_roles_dict['node_roles_dict'] }}"

- name: Calculate deleted nodes Dict
  set_fact:
    deleted_nodes_dict: "{{ cluster_roles_dict['deleted_nodes_dict'] }}"
