---
- name: Add ContrailVM to VM DVS
  vars: 
    vmname: "ContrailVM-{{ esxi_host.vcenter_server.datacentername }}-{{ esxi_host.name }}"
  vmware_guest:
    hostname: "{{ esxi_host.vcenter_server.hostname }}"
    username: "{{ esxi_host.vcenter_server.username }}"
    password: "{{ esxi_host.vcenter_server.password }}"
    validate_certs: "{{ esxi_host.vcenter_server.validate_certs }}"
    datacenter: "{{ esxi_host.vcenter_server.datacentername }}"
    cluster: "{{ esxi_host.cluster }}"
    name: "{{ esxi_host.contrail_vm.name | default (vmname) }}"
    networks:
      - name: "{{ esxi_host.vcenter_server.dv_port_group.dv_portgroup_name }}"
  async: 3600
  poll: 0
  register: vm_added

- name: Save vm add to DVS result
  set_fact:
   vms_added: "{{ vms_added | default([]) + [vm_added] }}"
