---
#- hosts:
#  - hypervisors
#  roles:
#  - image_builder
#  tags:
#  - build_vms
#
#- hosts:
#  - container_hosts
#  roles:
#  - configure_container_hosts
#  tags:
#  - configure_vms

- hosts:
  - container_hosts
  roles:
  - create_containers
  tags:
  - create_containers
