#CONTAINER_REGISTRY: michaelhenkel
CONTAINER_REGISTRY: satellite.englab.juniper.net:5443
REGISTRY_PRIVATE_SECURE: true
REGISTRY_PRIVATE_INSECURE: false
contrail_configuration:
  OPENSTACK_VERSION: ocata
  LINUX_DISTR: centos
  CONTRAIL_VERSION: 4.1.0.0-8
  CONTROLLER_NODES: 192.168.1.100,192.168.1.101,192.168.1.102
  CONTROL_NODES: 192.168.2.100,192.168.2.101,192.168.2.102
  #CLOUD_ORCHESTRATOR: kubernetes
  CLOUD_ORCHESTRATOR: openstack
  AUTH_MODE: keystone
  KEYSTONE_AUTH_ADMIN_PASSWORD: c0ntrail123
  KEYSTONE_AUTH_HOST: 192.168.1.254
  RABBITMQ_NODE_PORT: 5673
  PHYSICAL_INTERFACE: eth1
  VROUTER_GATEWAY: 192.168.2.1
roles:
  192.168.1.100:
    configdb:
    config:
    control:
    webui:
    analytics:
    analyticsdb:
#    k8s_master:
    vrouter:  
  192.168.1.101:
    configdb:
    config:
    control:
    webui:
    analytics:
    analyticsdb:
#    k8s_master:
    vrouter:
  192.168.1.102:
    configdb:
    config:
    control:
    webui:
    analytics:
    analyticsdb:
#    k8s_master:
    vrouter:
